### ISSUE TITLE
Hi srry to bother

### ISSUE THREAD

**Issue by loopy66** [SakuraKitsunee/ProdigyHacking--MobileHacking#31]
***What items should be in the account?***:
None don’t add anything it is my main acc
***What level do you want, how much gold, dark tower floor, etc?***:
Set my gold to 10000 don’t ask why.
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
apersonjust481@gmail.com is my email.

**Comment by SakuraKitsunee** [comment]
hey im here

**Comment by SakuraKitsunee** [comment]
what is the info? @loopy66

**Comment by loopy66** [comment]
Why this closed though?
