### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by obileuser** [SakuraKitsunee/ProdigyHacking--MobileHacking#33]
***What items should be in the account?***: Can I have every item possible please

***What level do you want, how much gold, dark tower floor, etc?***: as much gold and copper coins as possible idc about the dark tower and 3 of each rune and all the pets please

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
My email is icedragonvsfiredragon7@gmail.com thank you

**Comment by Prodigy-hack-yt** [comment]
What do you want your name to be?

**Comment by obileuser** [comment]
may my name be Shadow please if not you may choose

**Comment by obileuser** [comment]
thank you guys for helping me its kinda hard finding hacks for mobile

**Comment by SakuraKitsunee** [comment]
No problem, come back as much as you want if you want more accounts!

**Comment by Prodigy-hack-yt** [comment]
No problem just doing wat i like to do and @obileuserr lmk if i need to fix battle crash

**Comment by obileuser** [comment]
np

**Comment by Prodigy-hack-yt** [comment]
@obileuser that would mean a lot THANK YOU AS WELL !!!!!
