### ISSUE TITLE
Can I have another one? 

### ISSUE THREAD

**Issue by obileuser** [SakuraKitsunee/ProdigyHacking--MobileHacking#34]
***What items should be in the account?***:Everything if possible

***What level do you want, how much gold, dark tower floor, etc?***:Also everything if possible and max lvl

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:icedragonvsfiredragon7@gmail.com 

Can the name be Mateo moonshadow and can I have a member ship if possible I have reccomended it to some friends but I will reccomend it at school tmrw as well

**Comment by Prodigy-hack-yt** [comment]
Ok let me make it sorry my pc was updating

**Comment by obileuser** [comment]
your fine and thanks!

**Comment by obileuser** [comment]
I'm going to sleep so I won't know till tomorrow thx
