### ISSUE TITLE
Account request hello

### ISSUE THREAD

**Issue by PixelWolf1** [SakuraKitsunee/ProdigyHacking--MobileHacking#37]
***What items should be in the account?***:everything

***What level do you want, how much gold, dark tower floor, etc?***:infinite gold infinte copper coins max dark tower level max titan shrds lvl 100

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:pixelwolf7891@gmail.com

can you fix battle crash and may it have a member ship

**Comment by PixelWolf1** [comment]
anyone their

**Comment by PixelWolf1** [comment]
@irhrhd @hostedposted @Prodigy-hack-yt @SakuraKitsunee  is anyone their?

**Comment by SakuraKitsunee** [comment]
@PixelWolf1 would you like me to emial you the account or just send it here?

**Comment by PixelWolf1** [comment]
Email please

On Fri, May 21, 2021, 11:17 AM
Sa͉̓͜͞ķ̦͡͡u̼͆r̻̞̊͡a̼͊K̀ͅi͇̚t̩̫̫̂͐͘͘͢s̗̏u̖̜̖͉͗̒͑͛n͇͍̻̞̖̐̀̃͛͒ee͛͜ <

**Comment by SakuraKitsunee** [comment]
@PixelWolf1 I just emailed you the account info!
