### ISSUE TITLE
1 hacked account

### ISSUE THREAD

**Issue by urgayyyy** [SakuraKitsunee/ProdigyHacking--MobileHacking#39]
***What items should be in the account?***:
Just all the best items that you can get pls, doesn't matter
***What level do you want, how much gold, dark tower floor, etc?***:
lvl: 100 gold: 100,000-1,000,000 dark tower floor: 100
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***: pls contact me at adsadasdas50@gmail.com

**Comment by SakuraKitsunee** [comment]
@urgayyyy sure i ewmail the info to you or just post in on here

**Comment by SakuraKitsunee** [comment]
@urgayyyy check your inbox, I just emailed you!

**Comment by urgayyyy** [comment]
Can you email me the login info please, thank you!

**Comment by SakuraKitsunee** [comment]
@urgayyyy just did!!
