### ISSUE TITLE
i want every thing on my acc i want lvl 100 and 1000,000,000 gold and member ship my gmail is shortstrong665@gmail.com

### ISSUE THREAD

**Issue by savageboii2207** [SakuraKitsunee/ProdigyHacking--MobileHacking#41]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:

**Comment by Ao28th28thedev** [comment]
problem continuing like this
