### ISSUE TITLE
shortstrong665@gmail.com

### ISSUE THREAD

**Issue by savageboii2207** [SakuraKitsunee/ProdigyHacking--MobileHacking#42]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***l  i want everything on the acc i want lvl 100 and 1,000,000,000 gold and i want all curenncy at 1,000,000

**Comment by SakuraKitsunee** [comment]
@savageboii2207 just finshed, do you want me to email you the account info??

**Comment by savageboii2207** [comment]
yes please


On Fri, Jun 4, 2021 at 9:40 AM
Sa͉̓͜͞ķ̦͡͡u̼͆r̻̞̊͡a̼͊K̀ͅi͇̚t̩̫̫̂͐͘͘͢s̗̏u̖̜̖͉͗̒͑͛n͇͍̻̞̖̐̀̃͛͒ee͛͜ <

**Comment by SakuraKitsunee** [comment]
okay is that your email in the title?

**Comment by savageboii2207** [comment]
yes please and thank you so much

**Comment by savageboii2207** [comment]
??wdym??

On Fri, Jun 4, 2021 at 9:42 AM
Sa͉̓͜͞ķ̦͡͡u̼͆r̻̞̊͡a̼͊K̀ͅi͇̚t̩̫̫̂͐͘͘͢s̗̏u̖̜̖͉͗̒͑͛n͇͍̻̞̖̐̀̃͛͒ee͛͜ <

**Comment by SakuraKitsunee** [comment]
nvm, just just your inbox

**Comment by savageboii2207** [comment]
so ok


On Fri, Jun 4, 2021 at 9:44 AM
Sa͉̓͜͞ķ̦͡͡u̼͆r̻̞̊͡a̼͊K̀ͅi͇̚t̩̫̫̂͐͘͘͢s̗̏u̖̜̖͉͗̒͑͛n͇͍̻̞̖̐̀̃͛͒ee͛͜ <
