### ISSUE TITLE
I personally wouldn't trust this.

### ISSUE THREAD

**Issue by technobyteongithub** [SakuraKitsunee/ProdigyHacking--MobileHacking#43]
***Message***

As a head mod PMGH, I can assure you this is not what we do. We don't want others hacking others accounts as that's a breach of privacy. We are working on a solution for mobile. Please don't pose as a solution for mobile users. Feel free to contact my discord anytime. You can find me in #contact my dms are open.

**Comment by SakuraKitsunee** [comment]
hey this is real you can ask everyone and they would say it is real
