### ISSUE TITLE
my request

### ISSUE THREAD

**Issue by mehby2** [SakuraKitsunee/ProdigyHacking--MobileHacking#44]
What items should be in the account?:everything in my backpack, 2 of each epic, 3 crystal monsters,

What level do you want, how much gold, dark tower floor, etc?: level 100 100,000 gold,dark floor level 100,

Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)natelachance@outlook.com or thebigboimehb@gmail.com

**Comment by SakuraKitsunee** [comment]
@mehby2 can you make a account and complete the tutorial and then I Will be able to hack it for you! Is that okay? You  can just send the account info on here

**Comment by mehby2** [comment]
Username:mehb214
password:STOR0cks

**Comment by SakuraKitsunee** [comment]
what would you like your nickname to be in game?

**Comment by mehby2** [comment]
Nathaniel plant breath

**Comment by SakuraKitsunee** [comment]
okay got it! :)

**Comment by SakuraKitsunee** [comment]
@mehby2 what grade do you want your account to be?

**Comment by SakuraKitsunee** [comment]
user: mehbyyy

pass: mehby

**Comment by mehby2** [comment]
Grade 4

**Comment by SakuraKitsunee** [comment]
just gave you the info :)

**Comment by mehby2** [comment]
Why don’t I have gear only currency

**Comment by SakuraKitsunee** [comment]
let me fix that rq

**Comment by SakuraKitsunee** [comment]
check now is it good
