### ISSUE TITLE
stolen code?

### ISSUE THREAD

**Issue by TheFinality** [SakuraKitsunee/ProdigyHacking--MobileHacking#52]
***Describe your question***:

***Have you have sure this is not already a problem (Yes/No)***:

**Comment by TheFinality** [comment]
u stole hostedposted's code, he told me >:(

**Comment by SakuraKitsunee** [comment]
what code?? i am just using the prodigy hacking website

**Comment by TheFinality** [comment]
@SakuraKitsunee https://github.com/SakuraKitsunee/ProdigyHacking--MobileHacking/blob/main/Discord-Bot-ProdigyHacking
this is made by hostedposted

**Comment by SakuraKitsunee** [comment]
oh i did not put that in there it was @irhrhd do you want me too delete it?

**Comment by TheFinality** [comment]
ill ask hosted

**Comment by SakuraKitsunee** [comment]
what does it even do?

**Comment by SakuraKitsunee** [comment]
btw

**Comment by SakuraKitsunee** [comment]
ohhh ok
