### ISSUE TITLE
Account Request

### ISSUE THREAD

**Issue by MisakeTheRat** [SakuraKitsunee/ProdigyHacking--MobileHacking#57]
***What items should be in the account?***:
All the clothing, buddies, hats, ect and lots of currency and some mystics and good pets 
***What level do you want, how much gold, dark tower floor, etc?***:
lvl 100    10 mil gold tower 100 I want to have the membership too if possible if not that's fine! 
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***: My email is MisakeMotoko@gmail.com Thank you!

**Comment by MisakeTheRat** [comment]
Yeah sorry about the title thing- I didn't know you weren't supposed to put it, I didn't read so sorry-

**Comment by MisakeTheRat** [comment]
Also just incase I'm unable to check my email you can just join the classroom I made!

**Comment by MisakeTheRat** [comment]
This is the code! E53AB1D

**Comment by MisakeTheRat** [comment]
Once again I appreciate it! And if you respond late that's ok! I also have school so I understand

**Comment by SakuraKitsunee** [comment]
@MisakeTheRat Hi, are you there

**Comment by MisakeTheRat** [comment]
@SakuraKitsunee  Yes
